import hmac
import hashlib
import logging
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)


class VapiCustomer(BaseModel):
    number: Optional[str] = Field(None, description="Caller phone number")
    name: Optional[str] = Field(None, description="Caller name if provided")


class VapiCall(BaseModel):
    id: Optional[str] = Field(None, description="Vapi call unique ID")
    orgId: Optional[str] = Field(None, description="Vapi organization ID")
    type: Optional[str] = Field(None, description="Call type (inbound/outbound)")
    status: Optional[str] = Field(None, description="Call status")
    customer: Optional[VapiCustomer] = Field(None, description="Customer details")
    durationSeconds: Optional[float] = Field(0.0, description="Call duration in seconds")
    transcript: Optional[str] = Field(None, description="Full call transcript")
    summary: Optional[str] = Field(None, description="Call summary generated by Vapi")


class VapiMessage(BaseModel):
    type: Optional[str] = Field(None, description="Event message type e.g. end-of-call-report")
    call: Optional[VapiCall] = Field(None, description="Call object")
    artifact: Optional[Dict[str, Any]] = Field(None, description="Call artifact including transcript/recording")
    analysis: Optional[Dict[str, Any]] = Field(None, description="Call analysis")


class VapiWebhookPayload(BaseModel):
    message: Optional[VapiMessage] = Field(None, description="Vapi webhook message container")


class VapiService:
    @staticmethod
    def verify_signature(signature_header: Optional[str], raw_body: bytes, secret: str) -> bool:
        """
        Verify Vapi webhook secret/signature if secret is configured.
        If secret is empty or not set in dev, bypass or verify.
        """
        if not secret:
            return True  # If no webhook secret is configured, allow in dev mode
        
        if not signature_header:
            return False

        # Vapi signature verification header format or shared secret check
        # Vapi typically sends X-Vapi-Secret or HMAC SHA256 in x-vapi-signature
        if signature_header == secret:
            return True

        try:
            expected_signature = hmac.new(
                secret.encode("utf-8"),
                raw_body,
                hashlib.sha256
            ).hexdigest()
            return hmac.compare_digest(signature_header, expected_signature)
        except Exception as e:
            logger.error(f"Error verifying signature: {e}")
            return False

    @staticmethod
    def parse_end_of_call_report(payload: VapiWebhookPayload) -> Dict[str, Any]:
        """
        Safely extract transcript, caller phone number, call duration, and metadata from Vapi payload.
        """
        message = payload.message
        if not message:
            return {"valid": False, "reason": "Missing message object"}

        event_type = message.type
        call = message.call

        if not call:
            return {"valid": False, "reason": "Missing call object", "event_type": event_type}

        call_id = call.id
        customer = call.customer
        phone_number = customer.number if customer else "Unknown"
        caller_name = customer.name if customer else "Unknown Caller"
        duration = call.durationSeconds or 0.0
        transcript = call.transcript or ""
        summary = call.summary or ""

        # Check artifacts if transcript is empty in call object
        if not transcript and message.artifact:
            transcript = message.artifact.get("transcript", "")

        return {
            "valid": True,
            "event_type": event_type,
            "call_id": call_id,
            "phone_number": phone_number,
            "caller_name": caller_name,
            "duration_seconds": duration,
            "transcript": transcript,
            "summary": summary,
        }
