"""Initial migration with lead, call, and follow_up tables

Revision ID: 3d6d6fd9f4f3
Revises: 
Create Date: 2026-08-31 15:31:52.520834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6d6fd9f4f3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('language', sa.Enum('urdu', 'english', name='languageenum'), nullable=False),
    sa.Column('status', sa.Enum('new', 'hot', 'warm', 'cold', 'follow_up', name='leadstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('idx_lead_phone', 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_created_at'), 'leads', ['created_at'], unique=False)
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('qualification_score', sa.Enum('hot', 'warm', 'cold', name='qualificationscoreenum'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('language', sa.Enum('urdu', 'english', name='languageenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_created_at', 'calls', ['created_at'], unique=False)
    op.create_index('idx_call_lead_id', 'calls', ['lead_id'], unique=False)
    op.create_index(op.f('ix_calls_created_at'), 'calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_index(op.f('ix_calls_lead_id'), 'calls', ['lead_id'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_follow_up_lead_id', 'follow_ups', ['lead_id'], unique=False)
    op.create_index('idx_follow_up_scheduled_for', 'follow_ups', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_follow_ups_id'), 'follow_ups', ['id'], unique=False)
    op.create_index(op.f('ix_follow_ups_lead_id'), 'follow_ups', ['lead_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_scheduled_for'), 'follow_ups', ['scheduled_for'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_ups_scheduled_for'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_lead_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_id'), table_name='follow_ups')
    op.drop_index('idx_follow_up_scheduled_for', table_name='follow_ups')
    op.drop_index('idx_follow_up_lead_id', table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index(op.f('ix_calls_lead_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_created_at'), table_name='calls')
    op.drop_index('idx_call_lead_id', table_name='calls')
    op.drop_index('idx_call_created_at', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_at'), table_name='leads')
    op.drop_index('idx_lead_phone', table_name='leads')
    op.drop_index('idx_lead_created_at', table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
