"""add vapi_call_id to calls table

Revision ID: d42c20211bfb
Revises: 3d6d6fd9f4f3
Create Date: 2026-09-06 19:31:18.786026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42c20211bfb'
down_revision: Union[str, Sequence[str], None] = '3d6d6fd9f4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('vapi_call_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_calls_vapi_call_id'), 'calls', ['vapi_call_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_vapi_call_id'), table_name='calls')
    op.drop_column('calls', 'vapi_call_id')
    # ### end Alembic commands ###
